version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/corp-connect-dev/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: postgres-container
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=corp
      - POSTGRES_PASSWORD=2H?O?YwpC£~H5y4*
      - POSTGRES_DB=corpconnectdev

volumes:
  postgres_data: